server:
  port: 10001
logging:
  config: classpath:logback-spring.xml
  path: D:/logs/hope/api/biz
  level:
        org.hopeframework.biz.api: info
#相关配置文件
config:
  common:
    tempFilePath: D:/tempFiles/

spring:
  dubbo:
    scan: org.hopeframework.biz.api
    application:
      name: hope-biz-api
      owner: hope
    registry:
      address: zookeeper://114.55.30.32:2181
    protocol:
          name: dubbo
          port: 20881
    provider:
      timeout: 120000
      retries: -1
  redis:
    host: 114.55.30.32
    port: 34587
    password: tuodao!@#321
    database: 1
    pool:
      max-wait: 50
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.178.238.210:3306/td_business?autoCommit=false&useUnicode=true&characterEncoding=utf-8
    username: td_business
    password: td_business!@#123456
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 30
      minimum-idle: 3
      max-lifetime: 60000
      validation-timeout: 60000
      idle-timeout: 60000    
  sleuth:
    sampler:
      percentage: 1